# Generated by Django 4.2.11 on 2025-04-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_pizza_cartitem_post'),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='image',
        ),
        migrations.AddField(
            model_name='buy',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
            preserve_default=False,
        ),
    ]
