# Generated by Django 4.2.11 on 2025-04-12 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buy', '0002_remove_buy_cost_remove_buy_image_buy_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='usr',
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
