# Generated by Django 4.2.11 on 2025-04-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_cost'),
        ('buy', '0003_remove_buy_usr_buy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='cart',
        ),
        migrations.AddField(
            model_name='buy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='posts',
            field=models.ManyToManyField(related_name='buys', to='blog.post'),
        ),
    ]
