# Generated by Django 4.2.11 on 2025-04-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0006_buyitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='posts',
        ),
    ]
