# Generated by Django 4.0.5 on 2022-06-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='newpost-logo.png', upload_to='images/'),
            preserve_default=False,
        ),
    ]
