# Generated by Django 4.0.5 on 2022-06-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_images_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
