# Generated by Django 5.2 on 2025-04-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_specialcondition_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
