# Generated by Django 5.2 on 2025-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_bonuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuses',
            name='bonus_count',
            field=models.FloatField(default=0),
        ),
    ]
