# Generated by Django 4.2.11 on 2025-01-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='pizza',
            new_name='post',
        ),
    ]
